AppUnipsico/Models/Consulta.cs
using AppUnipsico.Enums;

namespace AppUnipsico.Models
{
    public class Consulta
    {
        public string ConsultaId { get; set; }
        public ConsultaEnum StatusConsulta { get; set; }

        public string UsuarioId { get; set; }
        public virtual Usuario Usuario { get; set; }

        public Guid DataConsultaId { get; set; }
        public virtual Datas DataConsulta { get; set; }
    }
}

AppUnipsico/ViewModels/ConsultaViewModel.cs
using AppUnipsico.Models;

namespace AppUnipsico.ViewModels
{
    public class ConsultaViewModel
    {
        public IEnumerable<Consulta> Consultas { get; set; }
    }
}

AppUnipsico/Controllers/ConsultaController.cs
using AppUnipsico.Models;
using AppUnipsico.Services.Interfaces;
using AppUnipsico.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AppUnipsico.Controllers
{
    [Authorize(Policy = "RequirePacienteRole")]
    public class ConsultaController : Controller
    {
        private readonly IConsultaService _consultaService;
        private readonly UserManager<Usuario> _userManager;
        private readonly IDataService _dataService;

        public ConsultaController(IConsultaService consultaService, UserManager<Usuario> userManager, IDataService dataService)
        {
            _consultaService = consultaService;
            _userManager = userManager;
            _dataService = dataService;
        }

        public async Task<IActionResult> Agendar(Guid DataConsultaId)
        {
            var usuario = await _userManager.GetUserAsync(User);

            if (usuario is null)
            {
                return View("Login");
            }

            var consulta = await _consultaService.CriaConsulta(DataConsultaId, usuario);
            if (consulta is not null)
            {
                await _dataService.AtualizaStatusData(consulta.DataConsultaId);
                return View("ConsultaAgendada", consulta);
            }

            return View();
        }

        public IActionResult ConsultaAgendada(Guid IdConsulta)
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ConsultaPaciente()
        {
            var usuario = await _userManager.GetUserAsync(User);

            var consultas = await _consultaService.BuscaConsultaPorUsuario(usuario);

            if (consultas is not null)
            {
                var consultaViewModel = new ConsultaViewModel
                {
                    Consultas = consultas,
                };

                return View(consultaViewModel);
            }
            else
            {
                ViewBag.MensagemInfo = "Nenhuma consulta encontrada!";
                return View();
            }
        }

        public async Task<IActionResult> ValidaEConfirmaConsultaNaSemana(Guid dataConsultaId)
        {
            var usuario = await _userManager.GetUserAsync(User);

            Consulta consultaNaSemana = await _consultaService.VerificaConsultaNaSemana(usuario, dataConsultaId);

            if (consultaNaSemana is not null)
            {
                var retornoModal = new ValidaConsultaViewModel
                {
                    Usuario = usuario,
                    Datas = consultaNaSemana.DataConsulta,
                    DataConsultaId = consultaNaSemana.DataConsultaId,
                    Consulta = consultaNaSemana,
                    ConsultaId = consultaNaSemana.DataConsultaId,
                    Mensagem = "Você já possui uma consulta agendada para esta semana.",
                };
                return View(retornoModal);
            }
            else
            {
                var data = await _dataService.BuscaDataPorId(dataConsultaId);

                var retornoModal = new ValidaConsultaViewModel
                {
                    Usuario = usuario,
                    DataConsultaId = data.Id,
                    Datas = data,
                    Consulta = null,
                    ConsultaId = null,
                    Mensagem = "Confirmar Consulta",
                };

                return View("ModalConfirmacaoConsulta", retornoModal);
            }
        }

    }
}

AppUnipsico/Controllers/DatasController.cs
using AppUnipsico.Services.Impl;
using AppUnipsico.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AppUnipsico.Controllers
{
    public class DatasController : Controller
    {
        private readonly DataService _datasServices;

        public DatasController(DataService dataDisponivelService)
        {
            _datasServices = dataDisponivelService;
        }

        [HttpGet]   
        public IActionResult Index()
        {
            var dataDisponivelViewModel = new DataViewModel()
            {
                DatasDisponiveis = _datasServices.DatasDisponiveis(),
            };

            return View(dataDisponivelViewModel);
        }
    }
}

AppUnipsico/Views/Consulta/ConsultaAgendada.cshtml
@using AppUnipsico.Utilities
@model Consulta
@{
    ViewData["Title"] = "Consulta Agendada";
}
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Detalhes da consulta</h3>
    </div>
    <hr />
    <div class="card">
        <div class="card-body">
            <p class="card-text"><strong>Id da Consulta:</strong> @Model.ConsultaId</p>
            <p class="card-text"><strong>Data da Consulta:</strong> @Model.DataConsulta.Data</p>
            <p class="card-text"><strong>Nome do Paciente:</strong> @Model.Usuario.Email</p>
            <p class="card-text"><strong>CPF do Paciente:</strong> @FormatUtility.InserePontoTracoCpf(Model.Usuario.Cpf)</p>
            <p class="card-text"><strong>Data de Nascimento do Paciente:</strong> @Model.Usuario.DataNascimento</p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Voltar para a página inicial</a>
        </div>
    </div>
</div>

AppUnipsico/Views/Consulta/ConsultaPaciente.cshtml
@model ConsultaViewModel

@{
    ViewBag.Title = "Consultas do Paciente";
}


<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="mb-3 text-left" style="color: white">Consultas</h3>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row mt-5 responsividade-cards">
                @if (Model.Consultas.Any())
                {
                    @foreach (var item in Model.Consultas)
                    {
                        <div class="col-8 col-sm-4 col-md-4 col-lg-3 mb-3">
                            <div class="card" style="border-top: 5px solid #00365d">
                                <div class="card-body d-flex flex-column">
                                    <div>
                                        <p class="text-sm mb-0 text-uppercase font-weight-bold">@item.DataConsulta.Data.ToShortDateString()</p>
                                        <h6 class="font-weight-bolder">@item.StatusConsulta</h6>
                                        <p class="font-weight-bold text-xs mb-0">@item.Usuario.NomeCompleto</p>
                                        <p class="font-weight-bolder mb-0">@item.DataConsulta.Data.ToShortTimeString()</p>
                                    </div>
@*                                     <div class="mt-auto text-end">
                                        <a asp-action="DetalhesConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-info-circle" aria-hidden="true"></i></a>
                                        <a asp-action="DeletarConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-trash" aria-hidden="true"></i></a>
                                    </div> *@
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-md-12">
                        <div class="alert alert-info" role="alert">
                            Não foram encontradas consultas.
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>





@* <div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-white text-left responsividade-textos-cabecalho">Suas Consultas</h3>
    </div>
    <hr />

    @if (Model.Consultas.Any())
    {
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Data da Consulta</th>
                                <th class="text-center">Horário da Consulta</th>
                                <th class="text-center">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var consulta in Model.Consultas)
                            {
                                <tr>
                                    <td class="text-center">@consulta.DataConsulta.Data.ToShortDateString()</td>
                                    <td class="text-center">@consulta.DataConsulta.Data.ToShortTimeString()</td>
                                    <td class="text-center">@consulta.StatusConsulta</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row justify-content-center mt-6">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <p class="text-center">Você não possui consultas agendadas no momento</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
 *@

AppUnipsico/Views/Consulta/ModalConfirmacaoConsulta.cshtml
@model ValidaConsultaViewModel
@{
    ViewData["Title"] = "Confirmar Consulta";
}
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Confirmar agendamento</h3>
    </div>
    <hr />
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Agendar Consulta</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <p><strong>CPF:</strong> @Model.Usuario.Cpf</p>
                    <p><strong>Email:</strong> @Model.Usuario.Email</p>
                    <p><strong>Data da Consulta:</strong> @Model.Datas.Data</p>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Datas" asp-action="Index" class="btn btn-secondary">Fechar</a>
            <a asp-area="" asp-controller="Consulta" asp-action="Agendar" asp-route-DataConsultaId="@Model.DataConsultaId" class="btn btn-primary">Confirmar Agendamento</a>
        </div>
    </div>
</div>

AppUnipsico/Views/Consulta/ValidaEConfirmaConsultaNaSemana.cshtml
@model ValidaConsultaViewModel

@{
    ViewData["Title"] = "Validar Consulta";
}
<div class="card">
    <div class="card-header bg-primary text-white">
        <h5 class="card-title">Consulta</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col">
                <p><strong>Mensagem:</strong> @Model.Mensagem</p>
                @if (Model.Consulta is not null)
                {
                    <p><strong>Consulta Id:</strong> @Model.Consulta.ConsultaId</p>
                    <p><strong>Data da Consulta:</strong> @Model.Consulta.DataConsulta.Data</p>
                    <p><strong>Status da Consulta:</strong> @Model.Consulta.StatusConsulta</p>
                }
            </div>
        </div>
    </div>
    <div class="card-footer text-center">
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Fechar</a>
        @if (Model.Consulta is not null)
        {
            <a asp-area="" asp-controller="Datas" asp-action="Index" class="btn btn-danger">Cancelar agendamento</a>
        }
    </div>
</div>