AppUnipsico/Areas/Admin/Controllers/AdminConsultasController.cs
using AppUnipsico.Areas.Admin.Repositories;
using AppUnipsico.Areas.Admin.ViewModels;
using AppUnipsico.Enums;
using AppUnipsico.Models;
using AppUnipsico.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppUnipsico.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "RequireAdminRole")]
    public class AdminConsultasController : Controller
    {
        private readonly ConsultasRepository _consultasRepository;
        private readonly DatasRepository _datasRepository;
        private readonly UserManager<Usuario> _userManager;

        public AdminConsultasController(ConsultasRepository consultasRepository, DatasRepository datasRepository, UserManager<Usuario> userManager)
        {
            _consultasRepository = consultasRepository;
            _datasRepository = datasRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var consultas = await _consultasRepository.BuscaTodasConsultas();

            return View(consultas);
        }

        [HttpGet]
        public async Task<IActionResult> CriarConsulta()
        {
            ViewBag.DatasDisponiveis = await _datasRepository.BuscaTodasDatasDisponiveis();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriarConsultaConfirmada(CriaConsultaViewModel criaConsultaViewModel)
        {
            if (ModelState.IsValid)
            {
                var formatadoCpf = FormatUtility.RemovePontoTracoCpf(criaConsultaViewModel.CpfPaciente);
                var paciente = await _userManager.Users.FirstOrDefaultAsync(c => c.Cpf == formatadoCpf
                                                                && c.TipoUsuario == TipoUsuarioEnum.Paciente);

                if (paciente is null)
                {
                    return View("PacienteNaoCadastrado");
                }

                var dataConsulta = await _datasRepository.BuscaDataPorId(criaConsultaViewModel.DataId);

                if (dataConsulta is null)
                {
                    return View("DataNaoEncotrada");
                }

                var consulta = new Consulta
                {
                    ConsultaId = Guid.NewGuid().ToString(),
                    StatusConsulta = ConsultaEnum.Agendada,
                    DataConsultaId = dataConsulta.Id,
                    DataConsulta = dataConsulta,
                    Usuario = paciente,
                    UsuarioId = paciente.Id,
                };

                var sucesso = await _consultasRepository.CriaConsulta(consulta);

                if (!sucesso.Erro)
                {
                    await _datasRepository.AtualizaStatusDaData(dataConsulta.Id, ConsultaEnum.Agendada);
                    return RedirectToAction("Index");
                }

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DetalhesConsulta(string consultaId)
        {
            var consulta = await _consultasRepository.BuscaConsultaPorId(consultaId);

            if (consulta is null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        [HttpGet]
        public async Task<IActionResult> EditarConsulta(string consultaId)
        {
            var consulta = await _consultasRepository.BuscaConsultaPorId(consultaId);

            if (consulta is null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        [HttpPost]
        public async Task<IActionResult> SalvarEdicaoConsulta(Consulta consulta)
        {
            var consultaEncontrada = await _consultasRepository.BuscaConsultaPorId(consulta.ConsultaId);

            if (consultaEncontrada is null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                consultaEncontrada.StatusConsulta = consulta.StatusConsulta;
                await _consultasRepository.SalvaEdicaoConsulta(consultaEncontrada);
                return RedirectToAction("Index");
            }

            return View("EditarConsulta", consulta);
        }

        public async Task<IActionResult> DeletarConsulta(string consultaId)
        {
            var consulta = await _consultasRepository.BuscaConsultaPorId(consultaId);

            if (consulta is null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        [HttpPost]
        public async Task<IActionResult> DeletarConsultaConfirmada(string consultaId)
        {
            var consulta = await _consultasRepository.BuscaConsultaPorId(consultaId);

            if (consulta is not null)
            {
                await _consultasRepository.DeletarConsulta(consulta);
                await _datasRepository.DeletarData(consulta.DataConsulta);

                return RedirectToAction("Index");
            }

            return View("Index", consulta);
        }
    }
}

AppUnipsico/Areas/Admin/Views/AdminConsultas/CriarConsulta.cshtml
@model CriaConsultaViewModel
@{
    ViewData["Title"] = "Agendar Consulta";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Criação de Consulta</h3>
    </div>
    <hr />
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card">
                <div class="card-body p-5">
                    <form asp-area="Admin" asp-controller="AdminConsultas" asp-action="CriarConsultaConfirmada" method="post">
                        <h4 class="text-center mb-4">Selecionar Data</h4>
                        <div class="row mb-4">
                            <div class="col">
                                <select id="DataId" name="DataId" asp-for="DataId" class="form-select">
                                    @foreach (var data in ViewBag.DatasDisponiveis)
                                    {
                                        <option value="@data.Id">@data.Data</option>
                                    }
                                </select>
                                <label for="DataId" class="ms-1 mt-1 form-label">Data da Consulta</label>
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col">
                                <input type="text" id="cpfPaciente" name="CpfPaciente" class="form-control" placeholder="Informe o CPF do paciente" />
                                <label for="cpfPaciente" class="ms-1 mt-1 form-label">CPF do Paciente</label>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn botoes-cor1 btn btn-block">Criar Consulta</button>
                            <a asp-controller="Admin" asp-action="Index" class="btn botoes-cor2 btn btn-block">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#cpfPaciente').mask('000.000.000-00', { reverse: false });
    </script>
}

AppUnipsico/Areas/Admin/Views/AdminConsultas/DataNaoEncontrada.cshtml
@{
    ViewData["Title"] = "Data de consulta não encontrada";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title">Data não encontrada</h1>
                    <p class="card-text">Por favor, verifique se a Data foi inserida corretamente.</p>
                </div>
            </div>
        </div>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminConsultas/DeletarConsulta.cshtml
@model Consulta

@{
    ViewData["Title"] = "Detalhes da Consulta";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Deseja deletar a consulta?</h3>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Detalhes da Consulta</h4>
                    <dl class="row">
                        <dt class="col-sm-4">Status da Consulta:</dt>
                        <dd class="col-sm-8">@Model.StatusConsulta</dd>

                        <dt class="col-sm-4">Nome do Usuário:</dt>
                        <dd class="col-sm-8">@Model.Usuario.NomeCompleto</dd>

                        <dt class="col-sm-4">CPF do Usuário:</dt>
                        <dd class="col-sm-8">@Model.Usuario.Cpf</dd>

                        <dt class="col-sm-4">Data de Nascimento do Usuário:</dt>
                        <dd class="col-sm-8">@Model.Usuario.DataNascimento</dd>

                        <dt class="col-sm-4">Tipo de Usuário:</dt>
                        <dd class="col-sm-8">@Model.Usuario.TipoUsuario</dd>

                        <dt class="col-sm-4">Data da Consulta:</dt>
                        <dd class="col-sm-8">@Model.DataConsulta.Data</dd>
                    </dl>
                    <form asp-controller="AdminConsultas" asp-action="DeletarConsultaConfirmada" method="post">
                        <input type="hidden" asp-for="ConsultaId" />
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger mr-2">Deletar</button>
                            <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminConsultas/DetalhesConsulta.cshtml
@model Consulta

@{
    ViewData["Title"] = "Detalhes";
}
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Detalhes da Consulta</h3>
    </div>
    <hr />
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Consulta</h4>

            <dl class="row">
                <dt class="col-sm-3">Status da Consulta:</dt>
                <dd class="col-sm-9">@Model.StatusConsulta</dd>

                <dt class="col-sm-3">Nome do Paciente:</dt>
                <dd class="col-sm-9">@Model.Usuario.NomeCompleto</dd>

                <dt class="col-sm-3">CPF do Paciente:</dt>
                <dd class="col-sm-9">@Model.Usuario.Cpf</dd>

                <dt class="col-sm-3">Data de Nascimento do Paciente:</dt>
                <dd class="col-sm-9">@Model.Usuario.DataNascimento.ToString("dd/MM/yyyy")</dd>

                <dt class="col-sm-3">Data da Consulta:</dt>
                <dd class="col-sm-9">@Model.DataConsulta.Data.ToString("dd/MM/yyyy")</dd>

                <dt class="col-sm-3">Horário da consulta:</dt>
                <dd class="col-sm-9">@Model.DataConsulta.Data.ToString("HH:mm")</dd>
            </dl>
        </div>
    </div>

    <div class="text-center mt-3">
        <a asp-action="Index" class="btn btn-secondary">Voltar para a Lista</a>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminConsultas/EditarConsulta.cshtml
@model Consulta

@{
    ViewData["Title"] = "Editar Consulta";
}
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Edição de Consulta</h3>
    </div>
    <br />

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Informações da Consulta</h4>
                    <form asp-action="SalvarEdicaoConsulta" asp-controller="AdminConsultas" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="ConsultaId" />
                        <div class="form-group">
                            <label asp-for="StatusConsulta" class="control-label">Status da Consulta:</label>
                            <select asp-for="StatusConsulta" class="form-control">
                                <option value="1">Disponível</option>
                                <option value="2">Agendada</option>
                                <option value="3">Concluída</option>
                                <option value="4">Cancelada</option>
                                <option value="5">Falta</option>
                                <option value="6">Remarcada</option>
                            </select>
                            <span asp-validation-for="StatusConsulta" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Usuario.NomeCompleto" class="control-label">Nome do usuário:</label>
                            <input asp-for="Usuario.NomeCompleto" class="form-control" readonly />
                            <span asp-validation-for="Usuario.NomeCompleto" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataConsulta.Data" class="control-label">Data da Consulta:</label>
                            <input asp-for="DataConsulta.Data" class="form-control" readonly />
                            <span asp-validation-for="DataConsulta.Data" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-outline-primary col-5">Salvar</button>
                            <a asp-controller="AdminConsultas" asp-action="Index" class="btn btn-outline-secondary col-5">Voltar para a Lista</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminConsultas/Index.cshtml
@model IEnumerable<AppUnipsico.Models.Consulta>

@{
    ViewData["Title"] = "Lista de consultas";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="mb-3 text-left" style="color: white">Consultas</h3>
    </div>
    <div class="d-flex justify-content-center mt-5">
        <a class="btn btn-success w-25 gap-2 d-flex justify-content-center align-items-center" asp-action="CriarConsulta">
            <i class="fa-lg bi-journal-check"></i> Agendar consulta
        </a>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row mt-5 responsividade-cards">
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-8 col-sm-4 col-md-4 col-lg-3 mb-3">
                            <div class="card" style="border-top: 5px solid #00365d">
                                <div class="card-body d-flex flex-column">
                                    <div>
                                        <p class="text-sm mb-0 text-uppercase font-weight-bold">@item.DataConsulta.Data.ToString("dd/MM/yyyy")</p>
                                        <h6 class="font-weight-bolder">@item.StatusConsulta</h6>
                                        <p class="font-weight-bold text-xs mb-0">@item.Usuario.NomeCompleto</p>
                                        <p class="font-weight-bolder mb-0">@item.DataConsulta.Data.ToString("HH:mm")</p>
                                    </div>
                                    <div class="mt-auto text-end">
                                        <a asp-action="DetalhesConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-info-circle" aria-hidden="true"></i></a>
                                        <a asp-action="EditarConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-pen-fancy"></i></a>
                                        <a asp-action="DeletarConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-trash" aria-hidden="true"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-md-12">
                        <div class="alert alert-info" role="alert">
                            Não foram encontradas consultas.
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>





@* 
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="mb-3 text-left" style="color: white">Consultas</h3>
    </div>
    <div class="d-flex justify-content-center mt-5">
        <a class="btn btn-success w-25 gap-2 d-flex justify-content-center align-items-center" asp-action="CriarConsulta"><i class="fa-lg bi-journal-check"></i>Agendar consulta</a>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row mt-5">
                @if (Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-md-2 mb-2 m-2">
                            <div class="card" style="border-top: 5px solid #00365d">
                                <div class="card-body d-flex flex-column">
                                    <div>
                                        <p class="text-sm mb-0 text-uppercase font-weight-bold">@item.DataConsulta.Data.ToShortDateString()</p>
                                        <h6 class="font-weight-bolder">@item.StatusConsulta</h6>
                                        <p class="font-weight-bold text-xs mb-0">@item.Usuario.NomeCompleto</p>
                                        <p class="font-weight-bolder mb-0">@item.DataConsulta.Data.ToShortTimeString()</p>
                                    </div>
                                    <div class="mt-auto text-end">
                                        <a asp-action="DetalhesConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-info-circle" aria-hidden="true"></i></a>
                                        <a asp-action="EditarConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-pen-fancy"></i></a>
                                        <a asp-action="DeletarConsulta" asp-route-ConsultaId="@item.ConsultaId"><i class="fas fa-trash" aria-hidden="true"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-md-12">
                        <div class="alert alert-info" role="alert">
                            Não foram encontradas consultas.
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


 *@

AppUnipsico/Areas/Admin/Views/AdminConsultas/PacienteNaoCadastrado.cshtml
@{
    ViewData["Title"] = "Paciente Não Encontrado";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title">Paciente não encontrado</h1>
                    <p class="card-text">O Paciente não foi encontrado.</p>
                    <p class="card-text">Por favor, verifique se o CPF foi inserido corretamente.</p>
                </div>
            </div>
        </div>
    </div>
</div>