AppUnipsico/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AppUnipsico.ViewModels
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Preencha o E-mail!")]
        [EmailAddress(ErrorMessage = "Informe um endereço de email válido.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Preencha o Nome!")]
        [Display(Name = "Nome Completo")]
        public string NomeCompleto { get; set; }

        [Required(ErrorMessage = "Preencha a Senha!")]
        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$",
        ErrorMessage = "A senha deve conter pelo menos 8 caracteres, uma letra maiúscula, um número e um caractere especial.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Preencha confirmando a senha.")]
        [Display(Name = "Confirme a senha")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "As senhas não conferem!")]
        public string Repassword { get; set; }

        [Required(ErrorMessage = "Preencha o CPF!")]
        public string Cpf { get; set; }

        [Required(ErrorMessage = "Prencha a Data de Nascimento!")]
        [Display(Name = "Data do Nascimento")]
        [DataType(DataType.DateTime)]
        public DateTime DataNascimento { get; set; }

        [Required(ErrorMessage = "Selecione um perfil!")]
        [Display(Name = "Perfil")]
        public string SelectedRole { get; set; }

        public string ReturnUrl { get; set; }
    }
}

AppUnipsico/Areas/Admin/Controllers/AdminUsuariosController.cs
using AppUnipsico.Areas.Admin.Repositories;
using AppUnipsico.Areas.Admin.ViewModels;
using AppUnipsico.Models;
using AppUnipsico.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppUnipsico.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "RequireAdminRole")]
    public class AdminUsuariosController : Controller
    {
        private readonly UsuarioRepository _usuarioRepository;
        private readonly UserManager<Usuario> _userManager;
        public AdminUsuariosController(UserManager<Usuario> userManager, UsuarioRepository usuarioRepository)
        {
            _userManager = userManager;
            _usuarioRepository = usuarioRepository;
        }

        public async Task<IActionResult> Index()
        {
            var usuarios = await _usuarioRepository.BuscaTodosUsuarios();
            return View(usuarios);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        public async Task<IActionResult> DetalhesUsuario(string usuarioId)
        {
            if (usuarioId is null)
            {
                return NotFound();
            }
            else
            {
                var usuario = await _usuarioRepository.BuscaUsuarioPorId(usuarioId);

                if (usuario is not null)
                {
                    var usuarioConsultas = await _usuarioRepository.BuscaConsultasPorUsuario(usuario);

                    if (usuarioConsultas is not null && usuarioConsultas.Count > 0)
                    {
                        var usuariodetalheViewModel = new UsuarioDetalheViewModel
                        {
                            Consultas = usuarioConsultas,
                            Usuario = usuario,
                            Mensagem = "",
                        };

                        return View(usuariodetalheViewModel);
                    }

                    return View(new UsuarioDetalheViewModel { Usuario = usuario, Consultas = null, Mensagem = $"Nenhuma consulta encontrada para o usuário {usuario.NomeCompleto}!" });
                }
                else
                {
                    return NotFound();
                }
            }
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistraUsuarioViewModel registraUsuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuarioCriado = await _usuarioRepository.CriaUsuario(registraUsuarioViewModel);

                if (usuarioCriado.Succeeded)
                {
                    return RedirectToAction("Index", new { area = "Admin" });
                }

                foreach (var error in usuarioCriado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(registraUsuarioViewModel);
        }

        public async Task<IActionResult> DeletarUsuario(string usuarioId)
        {
            if (usuarioId is null)
            {
                return NotFound();
            }

            var usuario = await _userManager.Users
                .Where(u => u.Id == usuarioId)
                .Include(u => u.Consultas)
                .ThenInclude(c => c.DataConsulta)
                .FirstOrDefaultAsync();

            if (usuario is null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string usuarioId)
        {

            if (usuarioId is null)
            {
                return BadRequest();
            }

            var usuario = await _userManager.FindByIdAsync(usuarioId);

            if (usuario is null)
            {
                return NotFound();
            }

            var resultUserManager = await _userManager.DeleteAsync(usuario);

            if (resultUserManager.Succeeded)
            {
                return RedirectToAction("Index", new { area = "Admin" });
            }
            else
            {
                foreach (var error in resultUserManager.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View("Error");
            }
        }
    }
}

AppUnipsico/Areas/Admin/Views/AdminUsuarios/DeletarUsuario.cshtml
@model Usuario
@{
    ViewData["Title"] = "Deletar usuário";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Deletar Usuário</h3>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Deletar Usuário</h4>

                    <p class="lead">Tem certeza de que deseja remover este Usuário?</p>

                    <div class="alert alert-info text-center" role="alert">
                        <p class="lead">Atenção, ao deletar usuário, suas consultas também serão excluídas!</p>
                    </div>

                    <dl class="row">
                        <dt class="col-sm-4">Id do Usuário:</dt>
                        <dd class="col-sm-8">@Model.Id</dd>

                        <dt class="col-sm-4">Nome completo:</dt>
                        <dd class="col-sm-8">@Model.NomeCompleto</dd>

                        <dt class="col-sm-4">Cpf:</dt>
                        <dd class="col-sm-8">@Model.Cpf</dd>

                        <dt class="col-sm-4">E-mail:</dt>
                        <dd class="col-sm-8">@Model.Email</dd>

                        <dt class="col-sm-4">Data de nascimento:</dt>
                        <dd class="col-sm-8">@Model.DataNascimento</dd>
                    </dl>

                    <form asp-controller="AdminUsuarios" asp-action="DeleteConfirmed" asp-route-UsuarioId="@Model.Id" method="post">
                        <input type="hidden" />
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger mr-2">Deletar</button>
                            <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminUsuarios/DetalhesUsuario.cshtml
@model UsuarioDetalheViewModel
@{
    ViewData["Title"] = "Detalhes do usuário";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Detalhes do Usuário</h3>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="card col-8">
            <div class="card-body">
                <h4 class="text-center card-title">Detalhes do Usuário</h4>
                <br />
                <table class="table table-striped" style="border-radius: 15px">
                    <tbody>
                        <tr>
                            <th scope="row">Nome completo:</th>
                            <td>@Model.Usuario.NomeCompleto</td>
                        </tr>
                        @if (Model.Usuario.TipoUsuario == AppUnipsico.Enums.TipoUsuarioEnum.Aluno)
                        {
                            <tr>
                                <th scope="row">RA:</th>
                                <td>@Model.Usuario.RA</td>
                            </tr>
                        }
                        <tr>
                            <th scope="row">Cpf:</th>
                            <td>@Model.Usuario.Cpf</td>
                        </tr>
                        <tr>
                            <th scope="row">E-mail:</th>
                            <td>@Model.Usuario.Email</td>
                        </tr>
                        <tr>
                            <th scope="row">Data de nascimento:</th>
                            <td>@Model.Usuario.DataNascimento.ToString("dd/MM/yyyy")</td>
                        </tr>
                        <tr>
                            <th scope="row">Data de registro no sistema:</th>
                            <td>@Model.Usuario.DataRegistro.ToString("dd/MM/yyyy")</td>
                        </tr>
                        <tr>
                            <th scope="row">Tipo de usuário:</th>
                            <td>@Model.Usuario.TipoUsuario</td>
                        </tr>
                    </tbody>
                </table>
                <div class="text-center">
                    <a class="btn btn-secondary" asp-action="Index">Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>


@if (Model.Consultas is not null && Model.Consultas.Any())
{
    <br />
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-center card-title">Detalhes das consultas</h4>
                    <br />
                    <div class="table-responsive" style="border-radius: 15px">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th class="text-center">Data da consulta</th>
                                    <th class="text-center">Horário da consulta</th>
                                    <th class="text-center">Status da Consulta</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var consulta in Model.Consultas)
                                {
                                    <tr>
                                        <td class="text-center">@consulta.DataConsulta.Data.ToString("dd/MM/yyyy")</td>
                                        <td class="text-center">@consulta.DataConsulta.Data.ToString("HH:mm")</td>
                                        <td class="text-center">@consulta.StatusConsulta</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="text-center card-title">Mensagem</h4>
                    <p class="text-center">@Model.Mensagem</p>
                </div>
            </div>
        </div>
    </div>
}

AppUnipsico/Areas/Admin/Views/AdminUsuarios/Index.cshtml
@using AppUnipsico.Utilities
@model IEnumerable<Usuario>

@{
    ViewData["Title"] = "Usuários";
}

<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="mb-3 text-left" style="color: white">Usuários</h3>
    </div>
    <div class="row justify-content-center mt-5">
        <a class="btn btn-success w-25 gap-2 d-flex justify-content-center align-items-center" asp-area="Admin" asp-controller="AdminUsuarios" asp-action="Register"><i class="fa-lg bi-person-add"></i> Criar novo usuário</a>
        <div class="mt-5">
            <div class="table-responsive" style="border-radius: 15px">
                <table class="table table-striped">
                    <thead class="table cor-unifaat">
                        <tr>
                            <th class="text-center text-white" scope="col">Nome Completo</th>
                            <th class="text-center text-white" scope="col">CPF</th>
                            <th class="text-center text-white" scope="col">Data de Nascimento</th>
                            <th class="text-center text-white" scope="col">Data de Registro</th>
                            <th class="text-center text-white" scope="col">E-mail</th>
                            <th class="text-center text-white" scope="col">Tipo</th>
                            <th class="text-center text-white" scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var usuario in Model)
                        {
                            <tr>
                                <td class="text-center">@usuario.NomeCompleto</td>
                                <td class="text-center">@usuario.Cpf</td>
                                <td class="text-center">@usuario.DataNascimento.ToString("dd/MM/yyyy")</td>
                                <td class="text-center">@usuario.DataRegistro.ToString("dd/MM/yyyy")</td>
                                <td class="text-center">@usuario.Email</td>
                                <td class="text-center">@usuario.TipoUsuario</td>
                                <td class="text-center">
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-primary rounded m-1" asp-controller="AdminUsuarios" asp-action="DetalhesUsuario" asp-route-UsuarioId="@usuario.Id">Detalhes</a>
                                        <a class="btn btn-outline-danger rounded m-1" asp-controller="AdminUsuarios" asp-action="DeletarUsuario" asp-route-UsuarioId="@usuario.Id">Deletar</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

AppUnipsico/Areas/Admin/Views/AdminUsuarios/Register.cshtml
@model RegistraUsuarioViewModel
@{
    ViewData["Title"] = "Registrar Usuário";
}
<div class="container-fluid">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Cadastrar novo usuário</h3>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="col-7">
            <div class="card">
                <div class="card-body p-5">
                    <h3 class="mb-5">Registrar Usuário</h3>
                    <form asp-area="Admin" asp-controller="AdminUsuarios" asp-action="Register" class="form-horizontal" method="post">
                        <input type="hidden" asp-for="ReturnUrl" />
                        <div class="row mb-3">
                            <div class="col-12">
                                <input asp-for="NomeCompleto" class="form-control"/>
                                <label class="ms-1 mt-1 form-label" asp-for="NomeCompleto">Nome completo</label>
                                <span asp-validation-for="NomeCompleto" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <input asp-for="Email" class="form-control"/>
                                <label class="ms-1 mt-1 form-label" asp-for="Email">E-mail</label>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">                            
                                <input asp-for="Cpf" placeholder="000.000.000-00" id="cpf" class="form-control" pattern="[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}" />
                                <label class="ms-1 mt-1 form-label" asp-for="Cpf">CPF</label>
                                <span asp-validation-for="Cpf" class="text-danger"></span>
                            </div>
                            <div class="col-6">                              
                                <input asp-for="DataNascimento" class="form-control" type="date"/>
                                <label class="ms-1 mt-1 form-label" asp-for="DataNascimento">Data de Nascimento</label>
                                <span asp-validation-for="DataNascimento" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">                               
                                <select asp-for="SelectedRole" class="form-control" id="SelectedRole">
                                    <option value="" disabled>Escolha um perfil</option>
                                    <option value="Aluno">Aluno</option>
                                    <option value="Professor">Professor</option>
                                    <option value="Admin">Administrador</option>
                                </select>
                                <label class="ms-1 mt-1 form-label" asp-for="SelectedRole"></label>
                                <span asp-validation-for="SelectedRole" class="text-danger"></span>
                            </div>
                            <div class="col-6">                           
                                <input id="raInput" asp-for="RA" class="form-control" pattern="[0-9]*"/>
                                <label id="raLabel" asp-for="RA">RA</label>
                                <span asp-validation-for="RA" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">       
                                <input asp-for="Password" type="password" class="form-control"/>
                                <label class="ms-1 mt-1 form-label" asp-for="Password">Senha</label>
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="col-6">               
                                <input asp-for="Repassword" type="password" class="form-control"/>
                                <label class="ms-1 mt-1 form-label" asp-for="Repassword">Confirmar Senha</label>
                                <span asp-validation-for="Repassword" class="text-danger"></span>
                            </div>
                        </div>
                        <br />
                        <div class="">
                            <button type="submit" class="btn btn-success btn-block">Registrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.getElementById('SelectedRole').addEventListener('change', function () {
            var selectedRole = this.value;
            var raInput = document.getElementById('raInput');
            var raLabel = document.getElementById('raLabel');

            if (selectedRole === 'Aluno') {
                raInput.style.display = 'block';
                raLabel.style.display = 'block';
            } else {
                raInput.style.display = 'none';
                raLabel.style.display = 'none';
            }
        });
    </script>
    <script>
        $('#cpf').mask('000.000.000-00', { reverse: false });
    </script>
    <script>
        $('#raInput').mask('0000000', { reverse: false });
    </script>
}